CREATE PROCEDURE ADD_PEDIDO(@NOMBRE VARCHAR(45), @ESTADO BIT, @IDPAIS INTEGER, @IDUSUARIO INTEGER)
AS
BEGIN
	-- ADD NOMBRE CLIENTE,ESTADO,IDPAIS, IDUSUARIO
	insert into pedido values(GETDATE(),@NOMBRE,@ESTADO,0,@IDPAIS,@IDUSUARIO);
	
	DECLARE @ID_PEDIDO INTEGER;
	SET @ID_PEDIDO = (SELECT SCOPE_IDENTITY());

	RETURN @ID_PEDIDO;
END


CREATE PROCEDURE ADD_DETPEDIDO(@PEDIDO INTEGER, @IDPRODUCTO INTEGER, @CANTIDAD INTEGER, @COSTO DECIMAL(28,0))
AS
BEGIN
	-- ADD NOMBRE CLIENTE,ESTADO,IDPAIS, IDUSUARIO
	insert into det_pedido values(@CANTIDAD,@COSTO,@PEDIDO,@IDPRODUCTO);
END