CREATE PROCEDURE ADD_PEDIDO(@NOMBRE VARCHAR(45), @ESTADO BIT, @TOTAL DECIMAL(28,0), @NIT INTEGER,@CORRELATIVO INTEGER,@IDPAIS INTEGER, @IDUSUARIO INTEGER)
AS
BEGIN
	-- ADD NOMBRE CLIENTE,ESTADO,IDPAIS, IDUSUARIO
	insert into pedido(fecha_pedido,nombre_cliente,estado,total,nit,pais_idpais,usuario_idusuario) values(GETDATE(),@NOMBRE,@ESTADO,@TOTAL,@NIT,@IDPAIS,@IDUSUARIO);
	
	DECLARE @ID_PEDIDO INTEGER;
	SET @ID_PEDIDO = (SELECT SCOPE_IDENTITY());

	RETURN @ID_PEDIDO;
END


CREATE PROCEDURE ADD_DETPEDIDO(@PEDIDO INTEGER, @IDPRODUCTO INTEGER, @CANTIDAD INTEGER, @COSTO DECIMAL(28,0))
AS
BEGIN
	-- ADD NOMBRE CLIENTE,ESTADO,IDPAIS, IDUSUARIO
	insert into det_pedido values(@CANTIDAD,@COSTO,@PEDIDO,@IDPRODUCTO);
END

drop table factura;

ALTER TABLE pedido 
ADD correlativo INT NOT NULL,
	nit INT NOT NULL;